# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

### Storm Apps default configuration values
### Specific configuration values can be overridden by config.yaml

##############################################################################
### global.* configs are general configurations
##############################################################################


##############################################################################
### apps.postagger.* configs are for the POS Tagger application
##############################################################################

apps.postagger.workers.num: 1

apps.postagger.spout.parallelism: 1
apps.postagger.spout.max.pending: 1000

apps.postagger.bolt.tokenizer.parallelism: 1
apps.postagger.bolt.tokenizer.logging: false

apps.postagger.bolt.preprocessor.parallelism: 2
apps.postagger.bolt.preprocessor.logging: false

apps.postagger.bolt.postagger.parallelism: 2
apps.postagger.bolt.postagger.logging: true

##############################################################################
### apps.sentiment.analysis.* configs are for the Sentiment Analysis application
##############################################################################

apps.sentiment.analysis.workers.num: 1

apps.sentiment.analysis.spout.parallelism: 1
apps.sentiment.analysis.spout.max.pending: 2000
apps.sentiment.analysis.spout.startup.sleep.ms: 20000 # 20 sec

apps.sentiment.analysis.bolt.tokenizer.parallelism: 2
apps.sentiment.analysis.bolt.tokenizer.logging: false

apps.sentiment.analysis.bolt.preprocessor.parallelism: 2
apps.sentiment.analysis.bolt.preprocessor.logging: false

apps.sentiment.analysis.bolt.postagger.parallelism: 2
apps.sentiment.analysis.bolt.postagger.logging: false

apps.sentiment.analysis.bolt.sentimentdetection.parallelism: 1
apps.sentiment.analysis.bolt.sentimentdetection.logging: true

##############################################################################
### apps.sentiment.analysis.svm.* configs are for the Sentiment Analysis SVM application
##############################################################################

# c3.8xlarge

apps.sentiment.analysis.svm.workers.num: 1

apps.sentiment.analysis.svm.workers.childopts: "-Xms16g -Xmx32g -XX:+UseG1GC"
apps.sentiment.analysis.svm.supervisor.childopts: "-Xmx8g -Xmx16g -XX:+UseG1GC"

apps.sentiment.analysis.svm.metrics.logging.consumer.parallelism: 1
apps.sentiment.analysis.svm.metrics.logging.consumer.intervall.sec: 10

apps.sentiment.analysis.svm.spout.parallelism: 1
apps.sentiment.analysis.svm.spout.max.pending: 150
apps.sentiment.analysis.svm.spout.startup.sleep.ms: 20000 # 20 sec

apps.sentiment.analysis.svm.bolt.tokenizer.parallelism: 1
apps.sentiment.analysis.svm.bolt.tokenizer.logging: false

apps.sentiment.analysis.svm.bolt.preprocessor.parallelism: 1
apps.sentiment.analysis.svm.bolt.preprocessor.logging: false

apps.sentiment.analysis.svm.bolt.postagger.parallelism: 3
apps.sentiment.analysis.svm.bolt.postagger.logging: false

apps.sentiment.analysis.svm.bolt.featuregeneration.parallelism: 2
apps.sentiment.analysis.svm.bolt.featuregeneration.logging: false

apps.sentiment.analysis.svm.bolt.svm.parallelism: 2
apps.sentiment.analysis.svm.bolt.svm.logging: false

